name: workhive-mgt-system
services:
  mssql-server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql-server
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "yemFkUAgY@CB"
      ACCEPT_EULA: "Y"
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P yemFkUAgY@CB -Q 'SELECT 1'"]
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - mssql-data:/var/opt/mssql
    networks:
      - workhive-network

volumes:
  mssql-data:

networks:
  workhive-network:
    driver: bridge
